project:
  type: website
  output-dir: docs

website:
  title: "Subin's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/subin6169
      - icon: twitter
        href: https://twitter.com/
format:
  html:
    theme: Minty
    css: styles.css

engines:
  python:
    path: ~\.conda\envs\myenv\python.exe


